name: hourly-scheduler

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  request:
    name: Request
    runs-on: ubuntu-latest
    steps:
      - name: Email
              run:
                curl --request GET \
                --url 'https://vercel.com/davwill19/feedbackserver/employees/test' \
